name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install backend dependencies (clean install)
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          rm -rf node_modules package-lock.json yarn.lock
          npm install

      # Step 3: Install frontend dependencies and build
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          rm -rf node_modules yarn.lock
          yarn install
          yarn run build

      # Step 4: Start backend with PM2
      - name: Start backend with PM2
        working-directory: ./backend
        run: |
          pm2 stop all || true
          pm2 start "npm run start" --name="backend"
          pm2 save
